using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FADatePicker.Win32
{
    [Flags]
    internal enum FlagsAnimateWindow : uint
    {
        AW_HOR_POSITIVE = 0x00000001,
        AW_HOR_NEGATIVE = 0x00000002,
        AW_VER_POSITIVE = 0x00000004,
        AW_VER_NEGATIVE = 0x00000008,
        AW_CENTER = 0x00000010,
        AW_HIDE = 0x00010000,
        AW_ACTIVATE = 0x00020000,
        AW_SLIDE = 0x00040000,
        AW_BLEND = 0x00080000
    }

    [Flags]
    internal enum FlagsSetWindowPos : uint
    {
        SWP_NOSIZE = 0x0001,
        SWP_NOMOVE = 0x0002,
        SWP_NOZORDER = 0x0004,
        SWP_NOREDRAW = 0x0008,
        SWP_NOACTIVATE = 0x0010,
        SWP_FRAMECHANGED = 0x0020,
        SWP_SHOWWINDOW = 0x0040,
        SWP_HIDEWINDOW = 0x0080,
        SWP_NOCOPYBITS = 0x0100,
        SWP_NOOWNERZORDER = 0x0200,
        SWP_NOSENDCHANGING = 0x0400,
        SWP_DRAWFRAME = 0x0020,
        SWP_NOREPOSITION = 0x0200,
        SWP_DEFERERASE = 0x2000,
        SWP_ASYNCWINDOWPOS = 0x4000
    }

    internal enum SystemParametersInfoActions : uint
    {
        GetBeep = 1,
        SetBeep = 2,
        GetMouse = 3,
        SetMouse = 4,
        GetBorder = 5,
        SetBorder = 6,
        GetKeyboardSpeed = 10,
        SetKeyboardSpeed = 11,
        LangDriver = 12,
        IconHorizontalSpacing = 13,
        GetScreenSaveTimeout = 14,
        SetScreenSaveTimeout = 15,
        GetScreenSaveActive = 16,
        SetScreenSaveActive = 17,
        GetGridGranularity = 18,
        SetGridGranularity = 19,
        SetDeskWallPaper = 20,
        SetDeskPattern = 21,
        GetKeyboardDelay = 22,
        SetKeyboardDelay = 23,
        IconVerticalSpacing = 24,
        GetIconTitleWrap = 25,
        SetIconTitleWrap = 26,
        GetMenuDropAlignment = 27,
        SetMenuDropAlignment = 28,
        SetDoubleClkWidth = 29,
        SetDoubleClkHeight = 30,
        GetIconTitleLogFont = 31,
        SetDoubleClickTime = 32,
        SetMouseButtonSwap = 33,
        SetIconTitleLogFont = 34,
        GetFastTaskSwitch = 35,
        SetFastTaskSwitch = 36,
        SetDragFullWindows = 37,
        GetDragFullWindows = 38,
        GetNonClientMetrics = 41,
        SetNonClientMetrics = 42,
        GetMinimizedMetrics = 43,
        SetMinimizedMetrics = 44,
        GetIconMetrics = 45,
        SetIconMetrics = 46,
        SetWorkArea = 47,
        GetWorkArea = 48,
        SetPenWindows = 49,
        GetFilterKeys = 50,
        SetFilterKeys = 51,
        GetToggleKeys = 52,
        SetToggleKeys = 53,
        GetMouseKeys = 54,
        SetMouseKeys = 55,
        GetShowSounds = 56,
        SetShowSounds = 57,
        GetStickyKeys = 58,
        SetStickyKeys = 59,
        GetAccessTimeout = 60,
        SetAccessTimeout = 61,
        GetSerialKeys = 62,
        SetSerialKeys = 63,
        GetSoundsEntry = 64,
        SetSoundsEntry = 65,
        GetHighContrast = 66,
        SetHighContrast = 67,
        GetKeyboardPref = 68,
        SetKeyboardPref = 69,
        GetScreenReader = 70,
        SetScreenReader = 71,
        GetAnimation = 72,
        SetAnimation = 73,
        GetFontSmoothing = 74,
        SetFontSmoothing = 75,
        SetDragWidth = 76,
        SetDragHeight = 77,
        SetHandHeld = 78,
        GetLowPowerTimeout = 79,
        GetPowerOffTimeout = 80,
        SetLowPowerTimeout = 81,
        SetPowerOffTimeout = 82,
        GetLowPowerActive = 83,
        GetPowerOffActive = 84,
        SetLowPowerActive = 85,
        SetPowerOffActive = 86,
        SetCursors = 87,
        SetIcons = 88,
        GetDefaultInputLang = 89,
        SetDefaultInputLang = 90,
        SetLangToggle = 91,
        GetWindwosExtension = 92,
        SetMouseTrails = 93,
        GetMouseTrails = 94,
        ScreenSaverRunning = 97,
        GetMouseHoverTime = 0x0066
    }

}
